enum ARC0300QueryEnum {
  Address = 'address',
  Asset = 'asset',
  Checksum = 'checksum',
  Fee = 'fee',
  FirstValid = 'firstvalid',
  GenesisHash = 'genesishash',
  Group = 'group',
  LastValid = 'lastvalid',
  Lease = 'lease',
  Name = 'name',
  Note = 'note',
  Page = 'page',
  PrivateKey = 'privatekey',
  ReyKeyTo = 'rekeyto',
  SelectionKey = 'selectionkey',
  StateProofKey = 'stateproofkey',
  Sender = 'sender',
  Type = 'type',
  VoteKeyDilution = 'votekeydilution',
  VoteFirst = 'votefirst',
  VoteKey = 'votekey',
  VoteLast = 'votelast',
}

export default ARC0300QueryEnum;
