enum StoreNameEnum {
  Accounts = 'accounts',
  AddAssets = 'add-assets',
  ARC0072Assets = 'arc0072-assets',
  ARC0200Assets = 'arc0200-assets',
  CredentialLock = 'credential-lock',
  CustomNodes = 'custom-nodes',
  Events = 'events',
  Messages = 'messages',
  Layout = 'layout',
  Networks = 'networks',
  News = 'news',
  Notifications = 'notifications',
  Passkeys = 'passkeys',
  Register = 'register',
  ReKeyAccount = 're-key-account',
  RemoveAssets = 'remove-assets',
  SendAssets = 'send-assets',
  Sessions = 'sessions',
  Settings = 'settings',
  StandardAssets = 'standard-assets',
  System = 'system',
}

export default StoreNameEnum;
