export const ACCOUNT_PAGE_HEADER_ITEM_HEIGHT: number = 10; // 2.5rem - 40px
export const DEFAULT_GAP: number = 6;
export const DEFAULT_POPUP_HEIGHT: number = 740;
export const DEFAULT_POPUP_WIDTH: number = 400;
export const MODAL_ITEM_HEIGHT: number = 6;
export const SIDEBAR_BORDER_WIDTH: number = 1;
export const SIDEBAR_ITEM_HEIGHT: number = 12;
export const SETTINGS_ITEM_HEIGHT: number = 16;
export const SIDEBAR_MIN_WIDTH: number = 40;
export const SIDEBAR_MAX_WIDTH: number = 250;
export const TAB_ITEM_HEIGHT: number = 16;
