export const ACCOUNT_INFORMATION_REFRESH_INTERVAL = 54000; // 54 seconds in milliseconds
export const ACCOUNT_INFORMATION_ANTIQUATED_TIMEOUT = 28000; // 28 seconds in milliseconds
export const CREDENTIALS_LOCK_DURATION_LOWEST = 60000; // 1 minute in milliseconds
export const CREDENTIALS_LOCK_DURATION_LOW = 120000; // 2 minutes in milliseconds
export const CREDENTIALS_LOCK_DURATION_NORMAL = 300000; // 5 minutes in milliseconds
export const CREDENTIALS_LOCK_DURATION_HIGH = 600000; // 10 minutes in milliseconds
export const CREDENTIALS_LOCK_DURATION_HIGHER = 900000; // 15 minutes in milliseconds
export const CREDENTIALS_LOCK_DURATION_HIGHEST = 1800000; // 30 minutes in milliseconds
export const DEFAULT_NOTIFICATION_DURATION = 6000; // 6 seconds in milliseconds
export const EXPORT_ACCOUNT_QR_CODE_DURATION = 1500; // 1.5 seconds in milliseconds
export const HEARTBEAT_DURATION = 20000; // 20 seconds in milliseconds
export const NETWORK_TRANSACTION_PARAMS_REFRESH_INTERVAL = 1800000; // 30 minutes in milliseconds
export const NETWORK_TRANSACTION_PARAMS_ANTIQUATED_TIMEOUT = 900000; // 15 minutes in milliseconds
export const NETWORK_CONNECTIVITY_CHECK_INTERVAL = 36000; // 36 seconds in milliseconds
export const NODE_REQUEST_DELAY = 100; // in milliseconds
export const QR_CODE_SCAN_INTERVAL = 3000; // 3 seconds in milliseconds
