export const ACCOUNT_INFORMATION_REFRESH_INTERVAL: number = 54000; // 54 seconds in milliseconds
export const ACCOUNT_INFORMATION_ANTIQUATED_TIMEOUT: number = 28000; // 28 seconds in milliseconds
export const DEFAULT_NOTIFICATION_DURATION: number = 6000; // 6 seconds in milliseconds
export const HEARTBEAT_DURATION: number = 20000; // 20 seconds in milliseconds
export const NETWORK_TRANSACTION_PARAMS_REFRESH_INTERVAL: number = 1800000; // 30 minutes in milliseconds
export const NETWORK_TRANSACTION_PARAMS_ANTIQUATED_TIMEOUT: number = 900000; // 15 minutes in milliseconds
export const NETWORK_CONNECTIVITY_CHECK_INTERVAL: number = 36000; // 36 seconds in milliseconds
export const NODE_REQUEST_DELAY: number = 100; // in milliseconds
export const PASSWORD_LOCK_DURATION_LOWEST: number = 60000; // 1 minute in milliseconds
export const PASSWORD_LOCK_DURATION_LOW: number = 120000; // 2 minutes in milliseconds
export const PASSWORD_LOCK_DURATION_NORMAL: number = 300000; // 5 minutes in milliseconds
export const PASSWORD_LOCK_DURATION_HIGH: number = 600000; // 10 minutes in milliseconds
export const PASSWORD_LOCK_DURATION_HIGHER: number = 900000; // 15 minutes in milliseconds
export const PASSWORD_LOCK_DURATION_HIGHEST: number = 1800000; // 30 minutes in milliseconds
export const QR_CODE_SCAN_INTERVAL: number = 3000; // 3 seconds in milliseconds
