export const ACCOUNT_NAME_BYTE_LIMIT = 32;
export const CUSTOM_NODE_BYTE_LIMIT = 16;
export const DEFAULT_TRANSACTION_INDEXER_LIMIT = 20;
export const EXPORT_ACCOUNT_PAGE_LIMIT = 5;
export const UPPER_TRANSACTION_INDEXER_LIMIT = 100;
export const SEARCH_ASSET_INDEXER_LIMIT = 100;
export const TRANSACTION_CONFIRMATION_ROUNDS = 4;
export const TRANSACTION_NOTE_BYTE_LIMIT = 1024;
